const colors = {
  light: {
    text: "#eaecef",
    tint: "#fcd535",
    background: "#0b0e11",
    foreground: "#eaecef",
    card: "#161a1e",
    cardForeground: "#eaecef",
    primary: "#fcd535",
    primaryForeground: "#0b0e11",
    secondary: "#1e2329",
    secondaryForeground: "#eaecef",
    muted: "#1e2329",
    mutedForeground: "#848e9c",
    accent: "#2b2f36",
    accentForeground: "#eaecef",
    destructive: "#f6465d",
    destructiveForeground: "#ffffff",
    success: "#0ecb81",
    successForeground: "#ffffff",
    border: "#2b2f36",
    input: "#2b2f36",
  },
  dark: {
    text: "#eaecef",
    tint: "#fcd535",
    background: "#0b0e11",
    foreground: "#eaecef",
    card: "#161a1e",
    cardForeground: "#eaecef",
    primary: "#fcd535",
    primaryForeground: "#0b0e11",
    secondary: "#1e2329",
    secondaryForeground: "#eaecef",
    muted: "#1e2329",
    mutedForeground: "#848e9c",
    accent: "#2b2f36",
    accentForeground: "#eaecef",
    destructive: "#f6465d",
    destructiveForeground: "#ffffff",
    success: "#0ecb81",
    successForeground: "#ffffff",
    border: "#2b2f36",
    input: "#2b2f36",
  },
  radius: 8,
};

export default colors;
